import React,{useEffect,useMemo,useState}from'react';
import{Activity,TrendingUp,Sparkles}from'lucide-react';
import{supabase}from'./supabase';
import ProfileAvatar from'./ProfileAvatar';
import'./energy-pulse.css';

function weekKey(date){const d=new Date(date);const day=d.getDay();d.setDate(d.getDate()-day);d.setHours(0,0,0,0);return d.toISOString().slice(0,10)}
function weekLabel(key){return new Date(`${key}T12:00:00`).toLocaleDateString('en-US',{month:'short',day:'numeric'})}
export default function EnergyPulse({company,people,ratings,onChange}){const[history,setHistory]=useState([]);useEffect(()=>{load()},[company?.id]);async function load(){if(!company?.id)return;const{data,error}=await supabase.from('energy_pulse_ratings').select('rating,rated_at').eq('company_id',company.id).order('rated_at',{ascending:false}).limit(500);if(error){console.error(error);return}setHistory(data||[])}const entered=people.map(p=>Number(ratings[p.id])).filter(v=>Number.isFinite(v));const teamAverage=entered.length?(entered.reduce((a,b)=>a+b,0)/entered.length).toFixed(1):'—';const trend=useMemo(()=>{const grouped={};history.forEach(r=>{const key=weekKey(r.rated_at);(grouped[key] ||= []).push(Number(r.rating))});return Object.entries(grouped).map(([key,vals])=>({key,avg:vals.reduce((a,b)=>a+b,0)/vals.length})).sort((a,b)=>a.key.localeCompare(b.key)).slice(-8)},[history]);const averagePct=teamAverage==='—'?0:(Number(teamAverage)/5)*100;return <section className="energyPulsePanel"><div className="energyPulseHead"><div className="energyIntro"><span className="eyebrow">ENERGY PULSE</span><h2>HOW'S THE TEAM SHOWING UP?</h2><p>One number. Gut check. 1.0 is empty. 5.0 is fully charged.</p></div><div className="energyAverage"><div className="energyAverageIcon"><Activity/></div><div className="energyAverageCopy"><span>TEAM ENERGY</span><div><b>{teamAverage}</b><small>/ 5.0</small></div><div className="energyAverageTrack"><i style={{width:`${averagePct}%`}}/></div></div></div></div><div className="energyPeople">{people.map(p=>{const value=ratings[p.id]??'';return <div className="energyPerson" key={p.id}><div className="energyIdentity"><ProfileAvatar person={p} size="sm"/><b>{p.full_name}</b></div><div className="energyInputWrap"><button type="button" onClick={()=>{const n=Number(value||1);onChange(p.id,Math.max(1,Math.round((n-.1)*10)/10))}}>−</button><input type="number" min="1" max="5" step="0.1" inputMode="decimal" value={value} onChange={e=>{const raw=e.target.value;if(raw==='')return onChange(p.id,'');const n=Math.max(1,Math.min(5,Number(raw)));onChange(p.id,Number.isFinite(n)?Math.round(n*10)/10:'')}} placeholder="—"/><button type="button" onClick={()=>{const n=Number(value||1);onChange(p.id,Math.min(5,Math.round((n+.1)*10)/10))}}>+</button><small>/ 5</small></div></div>})}</div><div className="energyTrend"><div className="energyTrendTitle"><div className="trendIcon"><TrendingUp/></div><div><b>TEAM ENERGY TREND</b><span>Weekly average from saved Wild60 meetings</span></div></div>{!trend.length?<div className="energyTrendEmpty"><Sparkles/><span>Your trend starts after the first saved Energy Pulse.</span></div>:<div className="energyTrendGrid">{trend.map(w=><div className="energyWeek" key={w.key}><span>{weekLabel(w.key)}</span><div className="energyBar"><i style={{width:`${(w.avg/5)*100}%`}}/></div><b>{w.avg.toFixed(1)}</b></div>)}</div>}</div></section>}
