import React,{useEffect,useMemo,useState}from'react';
import{CalendarDays,ChevronRight,Star,FileText,CheckCircle2}from'lucide-react';
import{supabase}from'./supabase';

function formatDate(v){if(!v)return'';return new Date(v).toLocaleString('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit'})}
function sameDay(a,b){if(!a||!b)return false;const x=new Date(a),y=new Date(b);return x.getFullYear()===y.getFullYear()&&x.getMonth()===y.getMonth()&&x.getDate()===y.getDate()}
function Block({title,items}){if(!items?.length)return null;return <div className="historyBlock"><b>{title}</b><ul>{items.map((x,i)=><li key={i}>{x}</li>)}</ul></div>}

export default function MeetingHistory({company}){
 const[meetings,setMeetings]=useState([]),[ratings,setRatings]=useState([]),[recaps,setRecaps]=useState([]),[selected,setSelected]=useState(null),[loading,setLoading]=useState(true);
 useEffect(()=>{load()},[company?.id]);
 async function load(){if(!company?.id)return;setLoading(true);const[{data:m,error:me},{data:r},{data:w}]=await Promise.all([supabase.from('meetings').select('*').eq('company_id',company.id).order('ended_at',{ascending:false}),supabase.from('meeting_ratings').select('*').eq('company_id',company.id),supabase.from('wild_recaps').select('*').eq('company_id',company.id).order('ended_at',{ascending:false})]);if(me)console.error(me);setMeetings(m||[]);setRatings(r||[]);setRecaps(w||[]);setSelected(x=>x||m?.[0]||null);setLoading(false)}
 const selectedRecap=useMemo(()=>{if(!selected)return null;const same=recaps.filter(r=>sameDay(r.ended_at||r.created_at,selected.ended_at||selected.created_at));if(!same.length)return null;const t=new Date(selected.ended_at||selected.created_at).getTime();return same.sort((a,b)=>Math.abs(new Date(a.ended_at||a.created_at).getTime()-t)-Math.abs(new Date(b.ended_at||b.created_at).getTime()-t))[0]},[selected,recaps]);
 const selectedRatings=ratings.filter(r=>r.meeting_id===selected?.id);
 const s=selectedRecap?.summary||{};
 return <div className="historyWorkspace"><div className="workspaceHead"><div><span className="eyebrow">COMPANY MEMORY</span><h2>MEETING HISTORY</h2><p>Every Wild60 you close lives here so the team can see what was decided, assigned, scored, and carried forward.</p></div></div>{loading?<p className="muted">Loading meeting history…</p>:!meetings.length?<div className="historyEmpty"><CalendarDays/><h3>NO SAVED WILD60 MEETINGS YET</h3><p>Finish a meeting and click Save + Close Meeting. It will show up here automatically.</p></div>:<div className="historyLayout"><div className="historyList">{meetings.map(m=><button key={m.id} className={`historyMeeting ${selected?.id===m.id?'active':''}`} onClick={()=>setSelected(m)}><div><b>{m.title}</b><span>{formatDate(m.ended_at||m.created_at)}</span></div><div className="historyScore"><Star/>{Number(m.rating_average||0).toFixed(1)}</div><ChevronRight/></button>)}</div>{selected&&<div className="historyDetail"><div className="historyDetailHead"><div><span className="eyebrow">SAVED WILD60</span><h3>{selected.title}</h3><p>{formatDate(selected.ended_at||selected.created_at)}</p></div><div className="historyBigScore"><Star/><b>{Number(selected.rating_average||0).toFixed(1)}</b><span>/10</span></div></div><div className="historyMeta"><div><small>TEAM RATINGS</small><b>{selectedRatings.length||selected.rating_count||0}</b></div><div><small>STATUS</small><b><CheckCircle2/> COMPLETED</b></div><div><small>WILD RECAP</small><b><FileText/> {selectedRecap?'SAVED':'NOT RECORDED'}</b></div></div>{selectedRecap?<><div className="historyHeadline">{s.headline||'Wild Recap saved for this meeting.'}</div><div className="historyBlocks"><Block title="WHAT WE WON" items={s.wild_wins}/><Block title="WHAT WE DECIDED" items={s.decisions}/><Block title="ROCKS IN PLAY" items={s.current_rocks}/><Block title="TO-DOS IN PLAY" items={s.current_todos}/><Block title="PRESSURE POINTS IN PLAY" items={s.current_pressure_points}/><Block title="LOCKED IN" items={s.locked_in}/><Block title="STILL OPEN" items={s.still_open}/></div>{selectedRecap.transcript&&<details className="historyTranscript"><summary>VIEW MEETING TRANSCRIPT</summary><p>{selectedRecap.transcript}</p></details>}</>:<div className="historyNoRecap"><p>This meeting was saved without a Wild Recap recording. The score and meeting record are still preserved.</p></div>}</div>}</div>}</div>
}
