import React,{useRef,useState}from'react';
import{Mic,Square,Brain,CheckCircle2,AlertTriangle,X}from'lucide-react';
import{supabase}from'./supabase';

function elapsed(start){const n=Math.max(0,Math.floor((Date.now()-start)/1000));return`${String(Math.floor(n/60)).padStart(2,'0')}:${String(n%60).padStart(2,'0')}`}
export default function WildRecap({company,people,rocks,todos,pressurePoints,session,onCreateAction,meetingScore}){
 const[recording,setRecording]=useState(false),[started,setStarted]=useState(0),[clock,setClock]=useState('00:00'),[processing,setProcessing]=useState(false),[recap,setRecap]=useState(null),[error,setError]=useState('');const rec=useRef(null),chunks=useRef([]),tick=useRef(null);
 async function start(){setError('');if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)return setError('Recording is not supported in this browser.');try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});const r=new MediaRecorder(stream);chunks.current=[];r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=()=>{stream.getTracks().forEach(t=>t.stop());processAudio(new Blob(chunks.current,{type:r.mimeType||'audio/webm'}),r.mimeType||'audio/webm')};rec.current=r;r.start(1000);const now=Date.now();setStarted(now);setClock('00:00');tick.current=setInterval(()=>setClock(elapsed(now)),1000);setRecording(true)}catch(e){setError(e.message||'Microphone access was not allowed.')}}
 function stop(){if(!rec.current)return;clearInterval(tick.current);rec.current.stop();setRecording(false)}
 async function processAudio(blob,mime){setProcessing(true);setError('');try{const ext=mime.includes('mp4')?'m4a':mime.includes('ogg')?'ogg':'webm';const path=`${company.id}/${session.user.id}/${Date.now()}.${ext}`;const{error:up}=await supabase.storage.from('wild-recap-recordings').upload(path,blob,{contentType:mime,upsert:false});if(up)throw up;const{data:signed,error:signErr}=await supabase.storage.from('wild-recap-recordings').createSignedUrl(path,900);if(signErr)throw signErr;const response=await fetch('/api/wild-recap',{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${session.access_token}`},body:JSON.stringify({signed_url:signed.signedUrl,filename:`wild60.${ext}`,company,people,rocks,todos,pressure_points:pressurePoints,recipients:people.filter(p=>p.email&&p.user_id).map(p=>p.email),meeting_score:meetingScore})});const data=await response.json();if(!response.ok)throw new Error(data.error||'Wild Recap failed');const{data:saved,error:saveErr}=await supabase.from('wild_recaps').insert({company_id:company.id,created_by:session.user.id,audio_path:path,transcript:data.transcript,summary:data.summary,suggestions:data.suggestions,started_at:started?new Date(started).toISOString():null,ended_at:new Date().toISOString(),emailed_at:data.emailed?new Date().toISOString():null}).select().single();if(saveErr)throw saveErr;setRecap({...data,id:saved.id})}catch(e){setError(e.message||'Wild Recap failed.')}finally{setProcessing(false)}}
 async function persistSuggestions(next){setRecap(r=>({...r,suggestions:next}));if(recap?.id)await supabase.from('wild_recaps').update({suggestions:next}).eq('id',recap.id)}
 async function accept(s,idx){try{await onCreateAction(s);const next=recap.suggestions.map((x,n)=>n===idx?{...x,accepted:true,dismissed:false}:x);await persistSuggestions(next)}catch(e){setError(e.message||'Could not create action.')}}
 async function dismiss(idx){try{const next=recap.suggestions.map((x,n)=>n===idx?{...x,dismissed:true,accepted:false}:x);await persistSuggestions(next)}catch(e){setError(e.message||'Could not dismiss suggestion.')}}
 function question(s){if(s.kind==='rock')return'Should this become a Rock?';if(s.kind==='pressure_point')return'Should this become a Pressure Point?';return'Should this become a To-Do?'}
 return <section className="wildRecap"><div className="recapTop"><div><span className="eyebrow">AI MEETING ASSISTANT</span><h2>WILD RECAP™</h2><p>The database is the truth. The AI is the listener.</p></div>{recording?<button className="recapStop" onClick={stop}><Square/>STOP + BUILD RECAP <b>{clock}</b></button>:<button className="recapRecord" onClick={start} disabled={processing}><Mic/>{processing?'BUILDING WILD RECAP…':'RECORD MEETING'}</button>}</div>{recording&&<div className="recordingNotice"><span className="recordDot"/>RECORDING ON — Make sure everyone knows this meeting is being recorded for notes and accountability.</div>}{processing&&<div className="recapThinking"><Brain/><div><b>WILD RECAP IS LISTENING BACK.</b><span>Transcribing the meeting, checking Wild60 for what is already captured, and finding anything that may have slipped through.</span></div></div>}{error&&<div className="recapError"><AlertTriangle/>{error}</div>}{recap&&<div className="recapResult"><div className="recapHeadline"><CheckCircle2/><div><span className="eyebrow">RECAP READY{recap.emailed?' • EMAILED TO TEAM':''}</span><h3>{recap.summary?.headline||'Wild60 captured.'}</h3></div></div><div className="recapColumns"><RecapBlock title="WHAT WE WON" items={recap.summary?.wild_wins}/><RecapBlock title="WHAT WE DECIDED" items={recap.summary?.decisions}/><RecapBlock title="ROCKS IN PLAY" items={recap.summary?.current_rocks}/><RecapBlock title="TO-DOS IN PLAY" items={recap.summary?.current_todos}/><RecapBlock title="PRESSURE POINTS IN PLAY" items={recap.summary?.current_pressure_points}/><RecapBlock title="LOCKED IN" items={recap.summary?.locked_in}/></div><div className="suggestions"><span className="eyebrow">HEARD, BUT NOT YET CAPTURED</span><h3>DOES THIS NEED TO LIVE IN WILD60?</h3>{!recap.suggestions?.filter(s=>!s.dismissed).length?<p className="muted">Nothing is waiting for a decision. Your Wild60 records now reflect the commitments you chose to capture.</p>:recap.suggestions.map((s,n)=>!s.dismissed&&<div className={`suggestionRow ${s.accepted?'accepted':''}`} key={n}><div><b>{s.title}</b><small>{s.reason}</small>{!s.accepted&&<strong className="suggestionQuestion">{question(s)}</strong>}</div>{s.accepted?<span className="acceptedLabel"><CheckCircle2/>CREATED IN WILD60</span>:<div className="suggestionChoices"><button className="yesChoice" onClick={()=>accept(s,n)}>YES</button><button className="noChoice" onClick={()=>dismiss(n)}><X/>NO</button></div>}</div>)}</div></div>}
 </section>
}
function RecapBlock({title,items=[]}){return <div className="recapBlock"><b>{title}</b>{items?.length?<ul>{items.map((x,i)=><li key={i}>{x}</li>)}</ul>:<span>Nothing captured.</span>}</div>}
