import React,{useEffect,useMemo,useState}from'react';
import{Activity,CheckCircle2,MessageCircle,Sparkles}from'lucide-react';
import{supabase}from'./supabase';
import ProfileAvatar from'./ProfileAvatar';
import'./wild-pulse.css';

const QUESTIONS=[
 {key:'feeling',label:'HOW ARE YOU FEELING?',sub:'Your overall mood today.'},
 {key:'energy',label:"HOW'S YOUR ENERGY?",sub:'How much do you have in the tank?'},
 {key:'focus',label:'HOW FOCUSED DO YOU FEEL?',sub:'How clear are you on what matters today?'},
 {key:'supported',label:'DO YOU FEEL SUPPORTED?',sub:'Do you feel like your team has your back?'}
];
const EMOJIS=[['😣','1'],['😕','2'],['😐','3'],['🙂','4'],['🔥','5']];
const today=()=>new Date().toISOString().slice(0,10);
const avg=o=>{const a=QUESTIONS.map(q=>Number(o[q.key])).filter(Number.isFinite);return a.length===4?a.reduce((x,y)=>x+y,0)/4:null};
export default function WildPulse({company,people,session}){
 const[rows,setRows]=useState([]),[mine,setMine]=useState({feeling:null,energy:null,focus:null,supported:null,note:''}),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false);
 const me=people.find(p=>p.user_id===session?.user?.id);
 useEffect(()=>{load()},[company?.id,me?.id]);
 async function load(){if(!company?.id)return;const start=new Date();start.setDate(start.getDate()-30);const{data,error}=await supabase.from('wild_pulse_checkins').select('*').eq('company_id',company.id).gte('checkin_date',start.toISOString().slice(0,10)).order('checkin_date',{ascending:false});if(error)return console.error(error);setRows(data||[]);const own=(data||[]).find(r=>r.person_id===me?.id&&r.checkin_date===today());if(own){setMine({feeling:own.feeling,energy:own.energy,focus:own.focus,supported:own.supported,note:own.note||''});setSaved(true)}}
 async function submit(){if(!me)return alert('Your login is not linked to a Team profile yet.');if(QUESTIONS.some(q=>!mine[q.key]))return alert('Tap one answer for each question.');setBusy(true);const payload={company_id:company.id,person_id:me.id,checkin_date:today(),feeling:Number(mine.feeling),energy:Number(mine.energy),focus:Number(mine.focus),supported:Number(mine.supported),note:mine.note||null,created_by:session.user.id,updated_at:new Date().toISOString()};const{error}=await supabase.from('wild_pulse_checkins').upsert(payload,{onConflict:'person_id,checkin_date'});setBusy(false);if(error)return alert(error.message);setSaved(true);await load()}
 const todays=rows.filter(r=>r.checkin_date===today());const teamAvg=todays.length?todays.reduce((s,r)=>s+avg(r),0)/todays.length:null;const peopleMap=Object.fromEntries(people.map(p=>[p.id,p]));
 const trend=useMemo(()=>{const d={};rows.forEach(r=>{(d[r.checkin_date]||=[]).push(avg(r))});return Object.entries(d).map(([date,a])=>({date,value:a.reduce((x,y)=>x+y,0)/a.length})).sort((a,b)=>a.date.localeCompare(b.date)).slice(-10)},[rows]);
 return <div className="pulseWorkspace"><div className="pulseHero"><div><span className="eyebrow">WILD PULSE™</span><h2>CHECK IN WITH YOUR PEOPLE.<br/><em>NOT UP ON YOUR PEOPLE.</em></h2><p>A quick daily read on how the team is really showing up.</p></div><div className="pulseTeamScore"><Activity/><span>TODAY'S TEAM PULSE</span><b>{teamAvg?teamAvg.toFixed(1):'—'}</b><small>/ 5.0 • {todays.length} OF {people.length} CHECKED IN</small></div></div>{me&&<section className="pulseCheckin"><div className="pulseCheckinHead"><div><span className="eyebrow">MY DAILY CHECK-IN</span><h3>{saved?'YOU’RE CHECKED IN.':'HOW ARE YOU SHOWING UP TODAY?'}</h3></div>{saved&&<span className="pulseDone"><CheckCircle2/>DONE TODAY</span>}</div><div className="pulseQuestions">{QUESTIONS.map(q=><div className="pulseQuestion" key={q.key}><div><b>{q.label}</b><span>{q.sub}</span></div><div className="pulseEmojis">{EMOJIS.map(([emoji,value])=><button type="button" key={value} className={String(mine[q.key])===value?'selected':''} onClick={()=>{setMine(x=>({...x,[q.key]:Number(value)}));setSaved(false)}}><strong>{emoji}</strong><small>{value}</small></button>)}</div></div>)}</div><label className="pulseNote"><MessageCircle/><div><b>ANYTHING YOUR LEADER SHOULD KNOW TODAY?</b><span>Optional — add context if there's something worth knowing.</span></div><textarea value={mine.note} onChange={e=>{setMine(x=>({...x,note:e.target.value}));setSaved(false)}} placeholder="Share a thought, win, pressure point, or leave it blank…"/></label><button className="pulseSubmit" disabled={busy} onClick={submit}>{busy?'CHECKING IN…':saved?'UPDATE TODAY’S CHECK-IN':'CHECK IN'}</button></section>}
 <section className="pulseDashboard"><div className="pulseSectionTitle"><div><span className="eyebrow">LEADERSHIP VIEW</span><h3>TODAY'S TEAM</h3></div><small>{new Date().toLocaleDateString('en-US',{weekday:'long',month:'long',day:'numeric'})}</small></div><div className="pulsePeople">{people.map(p=>{const r=todays.find(x=>x.person_id===p.id),a=r?avg(r):null;return <div className={`pulsePerson ${a&&a<3?'needsAttention':''}`} key={p.id}><ProfileAvatar person={p} size="lg"/><div className="pulsePersonName"><b>{p.full_name}</b><span>{r?r.note||'Checked in today':'Waiting on check-in'}</span></div><div className="pulsePersonScore"><b>{a?a.toFixed(1):'—'}</b><span>{a?(a>=4?'STRONG':a>=3?'STEADY':'CHECK IN'):'NOT YET'}</span></div></div>})}</div><div className="pulseTrend"><div><Sparkles/><b>TEAM PULSE TREND</b></div>{trend.length?<div className="pulseTrendBars">{trend.map(d=><div key={d.date}><i style={{height:`${Math.max(8,d.value/5*100)}%`}}/><span>{new Date(`${d.date}T12:00`).toLocaleDateString('en-US',{month:'numeric',day:'numeric'})}</span></div>)}</div>:<p>Your trend begins as the team checks in.</p>}</div></section></div>
}
